apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: nick-space  # Replace with your desired namespace
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
